language: go

go:
  - 1.3
  - 1.4
  - 1.5

install:
  - go get -t -v golang.org/x/tools/cmd/cover
  - go get -t -v -u github.com/golang/lint/golint
  - go get -t -v github.com/mattn/goveralls
  - go get -t -v ./...

script:
  - go test -covermode=count -coverprofile=./profile.cov .

after_success:
  - GOPATH=`pwd`:$GOPATH $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
  - cd $HOME/gopath/src/github.com/index0h/go-servicelocator
  - gofmt -s -e -l ./
  - golint ./... | grep -v 'comment'